### ISSUE TITLE
Azure Storage and Cognitive Services Tutorial- French Flag Images Causes Crash

### ISSUE THREAD

**Issue by AustT1996** [MSFTImagine/computerscience#32]
I just did this tutorial, and uploaded a few images which worked, but one particular image (attached) caused a crash and gave the following error. Might be a bug with Azure not recognizing it properly.
![flag_of_france](https://cloud.githubusercontent.com/assets/22754579/20082752/34ee3fc6-a526-11e6-9a07-9abc33379fca.png)

C:\Users\Austin\Downloads\hcs_azure_tutorial_test\server.js:154
                    throw err;
                    ^
StorageError: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:cdf93341-0001-006b-4c5c-39fc7b000000
Time:2016-11-08T01:05:56.5808549Z
    at Function.StorageServiceClient._normalizeError (C:\Users\Austin\Downloads\hcs_azure_tutorial_test\node_modules\azure-storage\lib\common\services\storageserviceclient.js:1146:23)
    at BlobService.StorageServiceClient._processResponse (C:\Users\Austin\Downloads\hcs_azure_tutorial_test\node_modules\azure-storage\lib\common\services\storageserviceclient.js:706:50)
    at Request.processResponseCallback [as _callback] (C:\Users\Austin\Downloads\hcs_azure_tutorial_test\node_modules\azure-storage\lib\common\services\storageserviceclient.js:306:37)
    at Request.self.callback (C:\Users\Austin\Downloads\hcs_azure_tutorial_test\node_modules\azure-storage\node_modules\request\request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\Users\Austin\Downloads\hcs_azure_tutorial_test\node_modules\azure-storage\node_modules\request\request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (C:\Users\Austin\Downloads\hcs_azure_tutorial_test\node_modules\azure-storage\node_modules\request\request.js:965:12)

**Comment by jeffprosise** [comment]
Thanks! I will check into it.

**Comment by shanamatthews** [comment]
Did this fixed? If not, let me know and I can reopen 😄

**Comment by AustT1996** [comment]
I have no idea- I did this for a random azure demo more than a year ago and
I think my account expired. I just googled "French Flag" and put in the
first image I saw, so if you want to repeat the issue just do that.

Kudos for responding to this after I had long forgotten about it- great
responsiveness!
